# Generated by Django 4.1.6 on 2023-03-10 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=128)),
                ("smtp_server", models.CharField(max_length=256)),
                ("smtp_port", models.IntegerField()),
                ("imap_server", models.CharField(max_length=256)),
                ("imap_port", models.IntegerField()),
            ],
        ),
    ]
