# Generated by Django 4.1.6 on 2023-03-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailaccount",
            name="password",
            field=models.CharField(max_length=500),
        ),
    ]
