# Generated by Django 4.1.6 on 2023-03-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0002_alter_emailaccount_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
            ],
        ),
    ]
