# Generated by Django 4.1.6 on 2023-03-10 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0003_contact"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="phone_number",
        ),
    ]
