# Generated by Django 4.1.6 on 2023-03-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0004_remove_contact_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
