# Generated by Django 4.1.6 on 2023-03-10 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0005_alter_contact_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
