# Generated by Django 4.1.6 on 2023-03-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("email_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_from", models.EmailField(max_length=254)),
                ("email_to", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=500)),
                ("message", models.TextField()),
            ],
        ),
    ]
